window.AHSM_REGION_MAP={
  ben:'West Africa',bfa:'West Africa',civ:'West Africa',cpv:'West Africa',gha:'West Africa',gmb:'West Africa',gin:'West Africa',gnb:'West Africa',lbr:'West Africa',mli:'West Africa',mrt:'West Africa',ner:'West Africa',nga:'West Africa',sen:'West Africa',sle:'West Africa',tgo:'West Africa',
  caf:'Central Africa',cmr:'Central Africa',cod:'Central Africa',cog:'Central Africa',gab:'Central Africa',gnq:'Central Africa',stp:'Central Africa',tcd:'Central Africa',
  bdi:'East & Southern Africa',com:'East & Southern Africa',dji:'East & Southern Africa',eri:'East & Southern Africa',eth:'East & Southern Africa',ken:'East & Southern Africa',lso:'East & Southern Africa',mdg:'East & Southern Africa',moz:'East & Southern Africa',mwi:'East & Southern Africa',nam:'East & Southern Africa',rwa:'East & Southern Africa',sdn:'East & Southern Africa',som:'East & Southern Africa',ssd:'East & Southern Africa',swz:'East & Southern Africa',tza:'East & Southern Africa',uga:'East & Southern Africa',zaf:'East & Southern Africa',zmb:'East & Southern Africa',zwe:'East & Southern Africa',ago:'East & Southern Africa',bwa:'East & Southern Africa',
  dza:'Middle East & North Africa',egy:'Middle East & North Africa',irq:'Middle East & North Africa',isr:'Middle East & North Africa',jor:'Middle East & North Africa',kwt:'Middle East & North Africa',lbn:'Middle East & North Africa',lby:'Middle East & North Africa',mar:'Middle East & North Africa',omn:'Middle East & North Africa',pse:'Middle East & North Africa',qat:'Middle East & North Africa',sau:'Middle East & North Africa',syr:'Middle East & North Africa',tun:'Middle East & North Africa',tur:'Middle East & North Africa',yem:'Middle East & North Africa',
  afg:'South & Central Asia',bgd:'South & Central Asia',btn:'South & Central Asia',ind:'South & Central Asia',kaz:'South & Central Asia',kgz:'South & Central Asia',lka:'South & Central Asia',mdv:'South & Central Asia',npl:'South & Central Asia',pak:'South & Central Asia',tjk:'South & Central Asia',tkm:'South & Central Asia',uzb:'South & Central Asia',
  chn:'East & Southeast Asia',idn:'East & Southeast Asia',jpn:'East & Southeast Asia',khm:'East & Southeast Asia',kor:'East & Southeast Asia',lao:'East & Southeast Asia',mmr:'East & Southeast Asia',mng:'East & Southeast Asia',mys:'East & Southeast Asia',phl:'East & Southeast Asia',prk:'East & Southeast Asia',sgp:'East & Southeast Asia',tha:'East & Southeast Asia',tls:'East & Southeast Asia',vnm:'East & Southeast Asia',
  aus:'Pacific',fji:'Pacific',kir:'Pacific',nzl:'Pacific',png:'Pacific',slb:'Pacific',ton:'Pacific',tuv:'Pacific',vut:'Pacific',wsm:'Pacific',
  alb:'Europe',aut:'Europe',aze:'Europe',bel:'Europe',bgr:'Europe',bih:'Europe',blr:'Europe',che:'Europe',cyp:'Europe',cze:'Europe',deu:'Europe',dnk:'Europe',esp:'Europe',est:'Europe',fin:'Europe',fra:'Europe',gbr:'Europe',geo:'Europe',grc:'Europe',hrv:'Europe',hun:'Europe',irl:'Europe',isl:'Europe',ita:'Europe',ltu:'Europe',lux:'Europe',lva:'Europe',mda:'Europe',mkd:'Europe',mlt:'Europe',mne:'Europe',nld:'Europe',nor:'Europe',pol:'Europe',prt:'Europe',rou:'Europe',rus:'Europe',srb:'Europe',svk:'Europe',svn:'Europe',swe:'Europe',ukr:'Europe',
  arg:'Latin America & Caribbean',blz:'Latin America & Caribbean',bol:'Latin America & Caribbean',bra:'Latin America & Caribbean',brb:'Latin America & Caribbean',chl:'Latin America & Caribbean',col:'Latin America & Caribbean',cri:'Latin America & Caribbean',cub:'Latin America & Caribbean',dom:'Latin America & Caribbean',ecu:'Latin America & Caribbean',gtm:'Latin America & Caribbean',guy:'Latin America & Caribbean',hnd:'Latin America & Caribbean',hti:'Latin America & Caribbean',jam:'Latin America & Caribbean',mex:'Latin America & Caribbean',nic:'Latin America & Caribbean',pan:'Latin America & Caribbean',per:'Latin America & Caribbean',pri:'Latin America & Caribbean',pry:'Latin America & Caribbean',slv:'Latin America & Caribbean',sur:'Latin America & Caribbean',tto:'Latin America & Caribbean',ury:'Latin America & Caribbean',ven:'Latin America & Caribbean',
  can:'North America',usa:'North America'
};
