const $=(s,r=document)=>r.querySelector(s);
const $$=(s,r=document)=>[...r.querySelectorAll(s)];
const norm=v=>String(v||'').trim().toLowerCase();
const safe=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
const STORAGE_SNAP='ahsm.temporal.snapshots.v1';
const STORAGE_WATCH='ahsm.temporal.watch.v1';
let snapshot=null,state=null;

function readLocal(key,fallback=[]){try{return JSON.parse(localStorage.getItem(key)||'null')??fallback;}catch{return fallback;}}
function writeLocal(key,value){localStorage.setItem(key,JSON.stringify(value));}
function reportFields(r={}){const pc=r.primaryCountry||r.primary_country?.name||r.primary_country?.[0]?.name||'';const iso=norm(r.primaryCountryIso3||r.primary_country?.iso3||r.primary_country?.[0]?.iso3);const source=typeof r.source==='string'?r.source:(r.source||[]).map(x=>x.shortname||x.name).join(', ');const themes=(r.themes||r.theme||[]).map?.(x=>typeof x==='string'?x:x.name)||[];return {...r,primaryCountry:pc,primaryCountryIso3:iso,source,themes,url:r.url_alias||r.url||r.href||'',dateOriginal:r.dateOriginal||r.date?.original||''};}
function dt(v){const d=new Date(v);return Number.isNaN(d.getTime())?null:d;}
function windowMs(k){return k==='24h'?86400000:k==='30d'?2592000000:604800000;}
function anchor(reports){const dates=reports.map(r=>dt(r.dateOriginal)).filter(Boolean).sort((a,b)=>b-a);return dates[0]||new Date(snapshot?.generatedAt||Date.now());}
function regionOf(iso){return window.AHSM_REGION_MAP?.[norm(iso)]||'Other / Global';}
function filters(){return {keyword:$('#network-search')?.value||'',theme:$('#network-theme')?.value||'',source:$('#network-source')?.value||'',country:$('#network-country')?.value||'',region:$('#network-region')?.value||''};}
function baseReports(){const f=filters();const q=norm(f.keyword),theme=norm(f.theme),source=norm(f.source),country=norm(f.country);return (snapshot?.reports||[]).map(reportFields).filter(r=>{if(country&&r.primaryCountryIso3!==country)return false;if(f.region&&regionOf(r.primaryCountryIso3)!==f.region)return false;if(source&&!norm(r.source).includes(source))return false;if(theme&&!r.themes.some(t=>norm(t).includes(theme)))return false;if(q&&!norm([r.title,r.primaryCountry,r.source,...r.themes].join(' ')).includes(q))return false;return true;});}
function slice(reports,key,offset=0){const a=anchor(reports),size=windowMs(key),end=new Date(a.getTime()-offset*size),start=new Date(end.getTime()-size);return {start,end,reports:reports.filter(r=>{const d=dt(r.dateOriginal);return d&&d>start&&d<=end;})};}
function graph(reports){const nodes=new Map(),edges=new Map();const add=(id,label,type)=>{if(!id)return;const n=nodes.get(id)||{id,label,type,reports:0};n.reports++;nodes.set(id,n);};const addEdge=(a,b,r)=>{if(!a||!b||a===b)return;const [x,y]=[a,b].sort(),id=x+'||'+y,e=edges.get(id)||{id,source:x,target:y,weight:0,evidence:[]};e.weight++;if(e.evidence.length<12)e.evidence.push({title:r.title,url:r.url,date:r.dateOriginal,source:r.source,country:r.primaryCountry});edges.set(id,e);};for(const r of reports){const entities=[];if(r.primaryCountryIso3){const id='c:'+r.primaryCountryIso3;add(id,r.primaryCountry||r.primaryCountryIso3.toUpperCase(),'country');entities.push(id);}for(const s of String(r.source||'').split(',').map(x=>x.trim()).filter(Boolean).slice(0,3)){const id='s:'+norm(s);add(id,s,'source');entities.push(id);}for(const t of (r.themes||[]).slice(0,6)){const id='t:'+norm(t);add(id,t,'theme');entities.push(id);}const u=[...new Set(entities)];for(let i=0;i<u.length;i++)for(let j=i+1;j<u.length;j++)addEdge(u[i],u[j],r);}const adj=new Map([...nodes.keys()].map(id=>[id,new Map()]));for(const e of edges.values()){adj.get(e.source)?.set(e.target,e.weight);adj.get(e.target)?.set(e.source,e.weight);}for(const n of nodes.values()){const a=adj.get(n.id)||new Map();n.degree=a.size;n.weighted=[...a.values()].reduce((s,x)=>s+x,0);}return {nodes:[...nodes.values()],edges:[...edges.values()],adj,reports};}
function communities(g){const labels=new Map(g.nodes.map((n,i)=>[n.id,i]));for(let k=0;k<12;k++){let changed=0;for(const n of [...g.nodes].sort((a,b)=>b.weighted-a.weighted)){const score=new Map();for(const [o,w] of g.adj.get(n.id)||[]){const l=labels.get(o);score.set(l,(score.get(l)||0)+w);}if(!score.size)continue;const best=[...score].sort((a,b)=>b[1]-a[1]||a[0]-b[0])[0][0];if(labels.get(n.id)!==best){labels.set(n.id,best);changed++;}}if(!changed)break;}const raw=new Map();for(const [id,l] of labels){if(!raw.has(l))raw.set(l,new Set());raw.get(l).add(id);}return raw;}
function lineage(cur,prev){const cg=communities(cur),pg=communities(prev),rows=[];for(const [cl,cs] of cg){let best=null;for(const [pl,ps] of pg){const inter=[...cs].filter(x=>ps.has(x)).length,uni=new Set([...cs,...ps]).size,j=uni?inter/uni:0;if(!best||j>best.score)best={prior:pl,score:j,overlap:inter};}rows.push({current:cl,prior:best?.score?best.prior:null,score:best?.score||0,size:cs.size,overlap:best?.overlap||0});}return rows.sort((a,b)=>b.size-a.size);}
function model(){const key=$('#temporal-window')?.value||'7d',base=baseReports(),c=slice(base,key,0),p=slice(base,key,1),cg=graph(c.reports),pg=graph(p.reports),pn=new Map(pg.nodes.map(n=>[n.id,n])),pe=new Map(pg.edges.map(e=>[e.id,e])),ce=new Map(cg.edges.map(e=>[e.id,e]));const nodeChanges=cg.nodes.map(n=>({...n,previous:pn.get(n.id)?.weighted||0,delta:n.weighted-(pn.get(n.id)?.weighted||0)}));return {key,currentSlice:c,previousSlice:p,current:cg,previous:pg,nodeChanges,emerging:cg.edges.filter(e=>!pe.has(e.id)).sort((a,b)=>b.weight-a.weight),disappearing:pg.edges.filter(e=>!ce.has(e.id)).sort((a,b)=>b.weight-a.weight),strengthened:cg.edges.filter(e=>pe.has(e.id)&&e.weight>pe.get(e.id).weight).map(e=>({...e,delta:e.weight-pe.get(e.id).weight})).sort((a,b)=>b.delta-a.delta),weakened:cg.edges.filter(e=>pe.has(e.id)&&e.weight<pe.get(e.id).weight).map(e=>({...e,delta:e.weight-pe.get(e.id).weight})).sort((a,b)=>a.delta-b.delta),lineage:lineage(cg,pg),filters:filters()};}
function label(id,m=state){return m.current.nodes.find(n=>n.id===id)?.label||m.previous.nodes.find(n=>n.id===id)?.label||id;}
function evidenceCard(e,type){const reports=e.evidence||[];return `<article class="evidence-card"><div><span class="eyebrow">${safe(type)}</span><h4>${safe(label(e.source))} ↔ ${safe(label(e.target))}</h4><p class="micro">Weight ${e.weight}${e.delta?` · Δ ${e.delta>0?'+':''}${e.delta}`:''} · ${reports.length} evidence report${reports.length===1?'':'s'} retained</p></div><div class="evidence-links">${reports.slice(0,5).map(r=>`<a href="${safe(r.url)}" target="_blank" rel="noopener"><strong>${safe(r.title)}</strong><small>${safe(r.country)} · ${safe(r.source)} · ${safe(String(r.date||'').slice(0,10))}</small></a>`).join('')||'<span class="micro">No retained report links for this edge.</span>'}</div><div class="evidence-actions"><button class="button ghost" data-watch-node="${safe(e.source)}">Watch ${safe(label(e.source))}</button><button class="button ghost" data-watch-node="${safe(e.target)}">Watch ${safe(label(e.target))}</button></div></article>`;}
function getWatch(){return readLocal(STORAGE_WATCH,[]);}function toggleWatch(id){const w=getWatch();const next=w.includes(id)?w.filter(x=>x!==id):[...w,id];writeLocal(STORAGE_WATCH,next);renderWatch();}
function renderWatch(){const host=$('#temporal-watch');if(!host||!state)return;const watch=getWatch(),prev=new Map(state.previous.nodes.map(n=>[n.id,n]));host.innerHTML=watch.length?watch.map(id=>{const n=state.current.nodes.find(x=>x.id===id)||state.previous.nodes.find(x=>x.id===id),now=state.current.nodes.find(x=>x.id===id)?.weighted||0,before=prev.get(id)?.weighted||0,d=now-before;return `<article class="watch-card"><button data-focus-watch="${safe(id)}"><span>${safe(n?.type||'entity')}</span><strong>${safe(n?.label||id)}</strong><small>weighted ${before} → ${now} · Δ ${d>=0?'+':''}${d}</small></button><button data-watch-node="${safe(id)}" class="icon-button" aria-label="Remove watch">×</button></article>`;}).join(''):'<p class="micro">No watched entities. Add entities from evidence cards.</p>';bindActions();}
function renderLineage(){const host=$('#community-lineage');if(!host||!state)return;host.innerHTML=state.lineage.slice(0,10).map(x=>`<div class="lineage-row"><span>Current C${x.current}</span><strong>${x.prior==null?'New cluster':`Prior C${x.prior}`}</strong><small>${Math.round(x.score*100)}% overlap · ${x.size} current nodes</small></div>`).join('')||'<p class="micro">No comparable communities.</p>';}
function renderEvidence(){const host=$('#temporal-evidence');if(!host||!state)return;const items=[...state.emerging.slice(0,3).map(e=>[e,'Emerging relationship']),...state.strengthened.slice(0,3).map(e=>[e,'Strengthening relationship']),...state.disappearing.slice(0,2).map(e=>[e,'Disappearing relationship'])];host.innerHTML=items.length?items.map(([e,t])=>evidenceCard(e,t)).join(''):'<p class="micro">No high-priority temporal relationship changes detected for this filtered comparison.</p>';bindActions();}
function packageData(){return {schema:'quanta.reliefweb.temporal-network.v1',generatedAt:new Date().toISOString(),window:state.key,filters:state.filters,currentPeriod:{from:state.currentSlice.start.toISOString(),to:state.currentSlice.end.toISOString(),reportCount:state.current.reports.length},previousPeriod:{from:state.previousSlice.start.toISOString(),to:state.previousSlice.end.toISOString(),reportCount:state.previous.reports.length},nodeChanges:state.nodeChanges.map(n=>({id:n.id,label:n.label,type:n.type,currentWeighted:n.weighted,previousWeighted:n.previous,deltaWeighted:n.delta})),relationships:{emerging:state.emerging,strengthened:state.strengthened,weakened:state.weakened,disappearing:state.disappearing},communityLineage:state.lineage,watchedEntities:getWatch(),provenance:{provider:'ReliefWeb',snapshotGeneratedAt:snapshot?.generatedAt||null,analyticalBoundary:'Information-network change is not independent evidence of humanitarian severity, causality, coordination, or influence.'}};}
function download(obj,name){const b=new Blob([JSON.stringify(obj,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(b);a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),500);}
function saveTemporal(){const all=readLocal(STORAGE_SNAP,[]),pkg=packageData(),entry={id:crypto.randomUUID?.()||String(Date.now()),savedAt:new Date().toISOString(),window:pkg.window,filters:pkg.filters,summary:{currentReports:pkg.currentPeriod.reportCount,previousReports:pkg.previousPeriod.reportCount,emerging:pkg.relationships.emerging.length,disappearing:pkg.relationships.disappearing.length},package:pkg};writeLocal(STORAGE_SNAP,[entry,...all].slice(0,20));renderSaved();}
function renderSaved(){const host=$('#temporal-snapshots');if(!host)return;const all=readLocal(STORAGE_SNAP,[]);host.innerHTML=all.length?all.map(x=>`<article class="snapshot-card"><button data-export-snapshot="${safe(x.id)}"><span>${safe(x.window)} · ${safe(String(x.savedAt).slice(0,19).replace('T',' '))}</span><strong>${safe(x.summary.currentReports)} current vs ${safe(x.summary.previousReports)} prior reports</strong><small>${safe(x.summary.emerging)} emerging · ${safe(x.summary.disappearing)} disappearing</small></button><button class="icon-button" data-delete-snapshot="${safe(x.id)}">×</button></article>`).join(''):'<p class="micro">No saved temporal investigations in this browser.</p>';bindActions();}
function bindActions(){for(const b of $$('[data-watch-node]'))if(!b.dataset.bound){b.dataset.bound='1';b.addEventListener('click',()=>toggleWatch(b.dataset.watchNode));}for(const b of $$('[data-export-snapshot]'))if(!b.dataset.bound){b.dataset.bound='1';b.addEventListener('click',()=>{const x=readLocal(STORAGE_SNAP,[]).find(y=>y.id===b.dataset.exportSnapshot);if(x)download(x.package,`ahsm-temporal-${x.window}-${x.id}.json`);});}for(const b of $$('[data-delete-snapshot]'))if(!b.dataset.bound){b.dataset.bound='1';b.addEventListener('click',()=>{writeLocal(STORAGE_SNAP,readLocal(STORAGE_SNAP,[]).filter(x=>x.id!==b.dataset.deleteSnapshot));renderSaved();});}}
function refresh(){if(!snapshot||!$('#temporal-investigation'))return;state=model();renderEvidence();renderLineage();renderWatch();renderSaved();}
function injectTemporal(){const base=$('#temporal-intelligence');if(!base||$('#temporal-investigation'))return;const panel=document.createElement('section');panel.id='temporal-investigation';panel.className='panel temporal-investigation';panel.innerHTML=`<div class="panel-head"><div><span class="eyebrow">TEMPORAL EVIDENCE & INVESTIGATION</span><h2>Package changes for analyst review</h2><p>Save the current comparison, inspect report-level evidence, track watched entities, and export the temporal graph for QAP workflows.</p></div><div class="actions"><button id="save-temporal" class="button ghost">Save snapshot</button><button id="export-temporal" class="button">Export temporal JSON</button></div></div><div class="temporal-investigation-grid"><section><h3>Evidence cards</h3><div id="temporal-evidence"></div></section><section><h3>Community lineage</h3><div id="community-lineage"></div><h3>Watched entities</h3><div id="temporal-watch"></div></section></div><section class="saved-temporal"><h3>Saved temporal investigations</h3><div id="temporal-snapshots"></div></section>`;base.insertAdjacentElement('afterend',panel);$('#save-temporal').addEventListener('click',saveTemporal);$('#export-temporal').addEventListener('click',()=>download(packageData(),`quanta-reliefweb-temporal-${state.key}.json`));$('#temporal-window')?.addEventListener('change',()=>setTimeout(refresh,0));for(const id of ['network-search','network-theme','network-source','network-country','network-region'])$('#'+id)?.addEventListener('input',()=>setTimeout(refresh,0));$('#network-reset')?.addEventListener('click',()=>setTimeout(refresh,0));}

function appFullscreenActive(){return document.fullscreenElement===document.documentElement||document.body.classList.contains('app-pseudo-fullscreen');}
function updateFullscreenButton(){const b=$('#app-fullscreen');if(!b)return;const on=appFullscreenActive();b.textContent=on?'⛶ Exit full screen':'⛶ App full screen';b.setAttribute('aria-pressed',String(on));}
async function toggleAppFullscreen(){try{if(document.fullscreenElement){await document.exitFullscreen();}else if(document.documentElement.requestFullscreen){await document.documentElement.requestFullscreen();}else document.body.classList.toggle('app-pseudo-fullscreen');}catch{document.body.classList.toggle('app-pseudo-fullscreen');}updateFullscreenButton();}
function injectAppFullscreen(){if($('#app-fullscreen'))return;const actions=$('.topbar .actions');if(!actions)return;const b=document.createElement('button');b.id='app-fullscreen';b.className='button ghost';b.type='button';b.setAttribute('aria-label','Toggle full screen for the entire ARAC Humanitarian Situation Monitor');b.textContent='⛶ App full screen';actions.prepend(b);b.addEventListener('click',toggleAppFullscreen);document.addEventListener('fullscreenchange',updateFullscreenButton);document.addEventListener('keydown',e=>{if(e.altKey&&e.key==='Enter'){e.preventDefault();toggleAppFullscreen();}if(e.key==='Escape'&&document.body.classList.contains('app-pseudo-fullscreen')){document.body.classList.remove('app-pseudo-fullscreen');updateFullscreenButton();}});}
async function init(){injectAppFullscreen();const r=await fetch('./data/snapshot.json',{cache:'no-store'});if(!r.ok)return;snapshot=await r.json();let tries=0;const wait=setInterval(()=>{injectTemporal();if($('#temporal-investigation')){clearInterval(wait);refresh();}else if(++tries>30)clearInterval(wait);},120);}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>init().catch(console.error),{once:true});else init().catch(console.error);
